services:
  - type: web
    name: mini-wordpress-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mini-wordpress-db
          property: connectionString
    scaling:
      minInstances: 1
      maxInstances: 1

databases:
  - name: mini-wordpress-db
    databaseName: miniwordpress
    user: miniwordpress 